Found 4 GPUs for rendering. Using device 0.
Found 4 GPUs for rendering. Using device 0.
Found 4 GPUs for rendering. Using device 0.
Using cpu device
Wrapping the env in a VecTransposeImage.
envs and model setup in 5.5536
starting to learn
-------------reset----------------
-------------reset----------------
-------------reset----------------
Logging to runs/3faf542j/test_1
Process ForkServerProcess-2:
Traceback (most recent call last):
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    observation, reward, done, info = env.step(data)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 90, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/ludvik/Desktop/rs_sb3/custom_gym_wrapper.py", line 112, in step
    ob_dict, reward, done, info = self.env.step(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/wrappers/domain_randomization_wrapper.py", line 237, in step
    return super().step(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/wrappers/wrapper.py", line 56, in step
    return self.env.step(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 419, in step
    reward, done, info = self._post_action(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 457, in _post_action
    reward = self.reward(action)
  File "/home/ludvik/Desktop/rs_sb3/custom_task.py", line 240, in reward
    if self._check_success():
  File "/home/ludvik/Desktop/rs_sb3/custom_task.py", line 421, in _check_success
    print(object_height = self.sim.data.body_xpos[self.object_body_id][2])
TypeError: 'object_height' is an invalid keyword argument for print()
Process ForkServerProcess-3:
Process ForkServerProcess-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    observation, reward, done, info = env.step(data)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    observation, reward, done, info = env.step(data)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 90, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 90, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/ludvik/Desktop/rs_sb3/custom_gym_wrapper.py", line 112, in step
    ob_dict, reward, done, info = self.env.step(action)
  File "/home/ludvik/Desktop/rs_sb3/custom_gym_wrapper.py", line 112, in step
    ob_dict, reward, done, info = self.env.step(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/wrappers/domain_randomization_wrapper.py", line 237, in step
    return super().step(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/wrappers/domain_randomization_wrapper.py", line 237, in step
    return super().step(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/wrappers/wrapper.py", line 56, in step
    return self.env.step(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/wrappers/wrapper.py", line 56, in step
    return self.env.step(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 419, in step
    reward, done, info = self._post_action(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 419, in step
    reward, done, info = self._post_action(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 457, in _post_action
    reward = self.reward(action)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 457, in _post_action
    reward = self.reward(action)
  File "/home/ludvik/Desktop/rs_sb3/custom_task.py", line 240, in reward
    if self._check_success():
  File "/home/ludvik/Desktop/rs_sb3/custom_task.py", line 240, in reward
    if self._check_success():
  File "/home/ludvik/Desktop/rs_sb3/custom_task.py", line 421, in _check_success
    print(object_height = self.sim.data.body_xpos[self.object_body_id][2])
  File "/home/ludvik/Desktop/rs_sb3/custom_task.py", line 421, in _check_success
    print(object_height = self.sim.data.body_xpos[self.object_body_id][2])
TypeError: 'object_height' is an invalid keyword argument for print()
TypeError: 'object_height' is an invalid keyword argument for print()
Traceback (most recent call last):
  File "test_train_model_local_multi.py", line 103, in <module>
    model.learn(total_timesteps = 400*3*8*5, log_interval= 1, tb_log_name="test",)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py", line 299, in learn
    return super(PPO, self).learn(
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 250, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 178, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 162, in step
    return self.step_wait()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/vec_env/vec_transpose.py", line 95, in step_wait
    observations, rewards, dones, infos = self.venv.step_wait()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 120, in step_wait
    results = [remote.recv() for remote in self.remotes]
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 120, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError